### PR TITLE
Add sphinx-argparse documentation

### PR DESCRIPTION
**Pull request by dholth**
### Description

This includes sphinx-argparse documentation for grayskull's cli. The cli was moved into a file not called `__main__` and rearranged a bit to make it clear we can import the parser without running the tool. A workflow should automatically publish these to github pages if the project is set up to accept pages from a workflow, instead of a special branch.

It would be nice to include README.md in the documentation, like https://github.com/conda/conda-package-streaming/blob/main/docs/index.md?plain=1#L26 ; had some trouble with sphinx errors when doing so.

### CODE REVIEW

**Comment by dholth** [comment]
> is that ready for review?

Yes, this PR is ready for review.

**Comment by marcelotrevisani** [comment]
Sorry for my delay
Thanks a lot for the contribution

**Review by marcelotrevisani — APPROVED** [review]

**Review by marcelotrevisani — APPROVED** [review]

**Comment by dholth** [comment]
@marcelotrevisani it looks like you need to set up github actions as a source for github pages, and then re-run the sphinx workflow. You can find me on the conda-forge chat if that would help.

**Comment by dholth** [comment]
It works!

**Comment by BastianZim** [comment]
Is there a link to the docs? I can't seem to find where they are deployed.

**Comment by jezdez** [comment]
@BastianZim https://conda.github.io/grayskull/

@marcelotrevisani there was an issue with the GitHub pages setting of the repo, it was still set up to deploy from the `gh-pages` branch (you can probably delete this now), and not directly via github actions, which is GitHub's new pages API

**Comment by BastianZim** [comment]
Oh nice -- thanks!

Might be good to link that in the readme?

**Pull request merged**
