### PR TITLE
Support Python-version-specific deps in poetry

### PR DESCRIPTION
**Pull request by xhochy**
Poetry also supports dependencies depending on the Python version. I have encountered this in the `nannyml` package.

### CODE REVIEW

**Comment by jakirkham** [comment]
Maybe we should configure Grayskull with this GitHub setting

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch#updating-your-pull-request-branch

**Comment by jakirkham** [comment]
In particular think the setting is here

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

**Comment by marcelotrevisani** [comment]
That is already enabled :)
It is because we have a conflict that needs to be addressed

**Comment by jakirkham** [comment]
Ah ok. I can't see as I don't have permissions here 😅

**Comment by xhochy** [comment]
The tests don't pass. I realised once I have pushed this, that the problem will be much more complex.

**Comment by ytausch** [comment]
xref #463 #535

**Comment by marcelotrevisani** [comment]
Closing this in favour of https://github.com/conda/grayskull/pull/592

**Pull request closed without merging**
