### PR TITLE
Fix support for `pyproject.toml` dependencies with multiple selectors

### PR DESCRIPTION
**Pull request by xylar**
### Description

It is common for the same dependency to have multiple selectors, like the following:
```
    - pandas >=1.5.3,<2.2  # [py<39]
    - pandas >=2.1.2,<2.2  # [py>=39]
```
This merge attempts to fully support this capability.

In several places in the code where dependencies are merged, care is now taken to allow multiple versions of the same package as long as they come from the same source.  This happens when merging `toml` and `setup` dependencies into `sdist` dependencies, and again when merging `sdist` dependencies with `pypi` dependencies.  It also takes place when removing redundancies later in the process of building a recipe.

In addition, because some strategies (namely parsing of `poetry` dependencies) add selectors early in the process, care has been taken not to drop selectors that may mistakenly be identified as tags or comments.

Finally, a fix has been added to identify that a package `is_arch` when it has selectors, just as it is identified as `is_arch` when "extras" are detected.

Four new pypi tests have been added and new testing has been added to the existing `test_run_requirements_sdist` test to ensure that multiple selectors for the same package are handled correctly.

### CODE REVIEW

**Comment by xylar** [comment]
@marcelotrevisani, as always, I would very much appreciate your input and review.

@lorepirri, this work builds on yours in #592.  I would very much appreciate your feedback as well.

I have put several days into learning my way around `grayskull` (and `souschef`), but I have to return to my normal work soon so I don't know how much time I'll be able to put into this in the next while.  That's just to say that, if I'm slow to respond, don't take that as a lack of interest.

**Review by marcelotrevisani — APPROVED** [review]
LGTM! Thanks again! :)

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani, as always, I would very much appreciate your input and review.
> 
> @lorepirri, this work builds on yours in #592. I would very much appreciate your feedback as well.
> 
> I have put several days into learning my way around `grayskull` (and `souschef`), but I have to return to my normal work soon so I don't know how much time I'll be able to put into this in the next while. That's just to say that, if I'm slow to respond, don't take that as a lack of interest.

the modification looks sensible to me, I believe we can integrate it, thanks!

Don't worry, I am not taking that as a lack of interest at all, I am very glad to the insights and inputs you are bringing to gray skull!

**Comment by xylar** [comment]
@marcelotrevisani, wonderful, thanks so much.  I'd like to follow up at some point when I have time with some updates to `--strict-conda-forge` but I think that's also a project for when I have a few free days.

**Pull request merged**
